### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by jrogers512** [MITRECND/WhoDat#12]
I'm running this in a vagrant Ubuntu 16.04.  VBox is port forwarding 8080 to 80, and here are the errors I see:

```
10.0.2.2 - - [09/Feb/2017:20:16:17 +0000] "GET / HTTP/1.1" 500 528
[Thu Feb 09 20:16:17.667820 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022] mod_wsgi (pid=6): Target WSGI script '/opt/WhoDat/pydat/pydat/wsgi.py' cannot be loaded as Python module.
[Thu Feb 09 20:16:17.667847 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022] mod_wsgi (pid=6): Exception occurred processing WSGI script '/opt/WhoDat/pydat/pydat/wsgi.py'.
[Thu Feb 09 20:16:17.667868 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022] Traceback (most recent call last):
[Thu Feb 09 20:16:17.667889 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022]   File "/opt/WhoDat/pydat/pydat/wsgi.py", line 31, in <module>
[Thu Feb 09 20:16:17.667920 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022]     application = get_wsgi_application()
[Thu Feb 09 20:16:17.667930 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022]   File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Thu Feb 09 20:16:17.667958 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022]     django.setup()
[Thu Feb 09 20:16:17.667967 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022]   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 17, in setup
[Thu Feb 09 20:16:17.667988 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Thu Feb 09 20:16:17.667997 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__
[Thu Feb 09 20:16:17.668019 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022]     self._setup(name)
[Thu Feb 09 20:16:17.668027 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup
[Thu Feb 09 20:16:17.668047 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022]     self._wrapped = Settings(settings_module)
[Thu Feb 09 20:16:17.668055 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99, in __init__
[Thu Feb 09 20:16:17.668075 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Thu Feb 09 20:16:17.668083 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Thu Feb 09 20:16:17.668106 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022]     __import__(name)
[Thu Feb 09 20:16:17.668114 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022]   File "/opt/WhoDat/pydat/pydat/settings.py", line 233, in <module>
[Thu Feb 09 20:16:17.668133 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022]     execfile(csfile)
[Thu Feb 09 20:16:17.668152 2017] [wsgi:error] [pid 6:tid 140672902043392] [remote 10.0.2.2:33022] IOError: [Errno 21] Is a directory: '/opt/WhoDat/pydat/pydat/custom_settings.py'

```

**Comment by Mraoul** [comment]
It says custom_settings.py is a directory? Could you double check what that looks like? 

Also, I'm not sure if you're using the master branch, but if you're using the code directly, I'd recommend using the django_updates branch. Alternatively, there is a docker image that should work.
